name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4 # version is determined from the packageManager field in package.json by default.

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependency
        timeout-minutes: 5
        run: pnpm install

      - name: Build Storybook
        run: pnpm build:storybook

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_branch: gh-pages
          destination_dir: pr-${{ github.event.pull_request.number }}
          publish_dir: storybook-static

      - name: Run lint
        timeout-minutes: 5
        run: pnpm lint

      - name: Run tests
        timeout-minutes: 5
        run: pnpm test:coverage

      - name: Report Coverage
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
